export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT' 
export const CHANGE_THEME = 'CHANGE_THEME'
export const DISABLE_BUTTONS = 'DISABLE_DUTTONS'
export const ENABLE_BUTTONS = 'ENABLE_DUTTONS'
 